ingress-nginx:
  enabled: true

  controller:
    kind: DaemonSet
    hostPort:
      enabled: true
    service:
      externalTrafficPolicy: "Local" #To make real-ip works, need to restart pod
      enabled: false
    config:
      enable-real-ip: "true"
