apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello
spec:
  replicas: 1 
  template:
    metadata:
      labels:
        app: hello
    spec:
      containers:
      - name: hello-container
        image: hello-world:latest
        ports: 
        - containerPort: 8080
