apiVersion: v1
kind: Service
metadata:
  name: hello-nodeport
spec:
  type: NodePort
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8080
    nodePort: 30200
  selector:
    app: hello
